WodApp/WodApp/Areas/Administration/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WodApp.Areas.Administration.Controllers
{

    [Area("Administration")]
    public class TestController : Controller
    {
        
        [Authorize(Policy = "AdminOnly")]

        public IActionResult Index()
        {
            return View();
        }
    }
}

WodApp/WodApp/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Wod.Models.WodApp.VIewModels.Post;
using Wod.Services.PostService.Contracts;
using Wod.Services.VoteService.Contracts;

namespace WodApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IPostService postService;
        private readonly IVoteSysService voteSysService;

        public CategoryController(IPostService postService,IVoteSysService voteSysService)
        {
            this.postService = postService;
            this.voteSysService = voteSysService;
        }

        
        public IActionResult Index(string category)
        {
            var model = new IndexPostViewModel
            {
                Posts = postService.GetAllPostFromCategory(category)
            };

            foreach (var post in model.Posts)
            {
                post.VoteCount = voteSysService.GetVoteCount(post.Id);
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["userId"] = userId;
            return View(model);
        }
    }
}

WodApp/WodApp/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Wod.Data;
using Wod.Models.WodApp.Inputmodels;
using Wod.Services.CategoryService.Contracts;
using Wod.Services.Claudinary;
using Wod.Services.Claudinary.Contracts;
using Wod.Services.PostService.Contracts;
using Wod.Services.VoteService.Contracts;

namespace WodApp.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly ICloudinaryService cloudinaryService;
        private readonly ICategoryService categoryService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IVoteSysService voteSysService;

        public PostController(IPostService postService , ICloudinaryService cloudinaryService,
            ICategoryService categoryService, UserManager<ApplicationUser> userManager,IVoteSysService voteSysService)
        {
            this.postService = postService;
            this.cloudinaryService = cloudinaryService;
            this.categoryService = categoryService;
            this.userManager = userManager;
            this.voteSysService = voteSysService;
        }
        public IActionResult Index()
        {

            return View();
        }

        public async Task<IActionResult> ShowPost(int id)
        {
            var model = await postService.GetAsync(id);
            model.VoteCount = voteSysService.GetVoteCount(model.Id);
            return View(model);
        }


        public IActionResult Create()
        {
       
            var categories = this.categoryService.GetAll();
            var model = new CreatePostInputModel
            {
                Categoryes = categories,
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePostInputModel model)
        {
            var categories = this.categoryService.GetAll();
            model.Categoryes = categories;
            


            var user = await this.userManager.GetUserAsync(this.User);
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }
            var coverUrl = await this.cloudinaryService
                .UploadAsync(model.PictureUrl, User.Identity.Name);
            var date = DateTime.UtcNow;
          var postId =  await postService.GreateAsyns(model.Tittle, model.CategoryId, user.Id, date, coverUrl);
            return this.RedirectToAction("ShowPost", new { id= postId});
        }

    }
}

WodApp/WodApp/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Wod.Data;
using Wod.Models.WodApp.VIewModels;
using Wod.Services.PostService.Contracts;
using Wod.Services.ProfileService.Contracts;

namespace WodApp.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly UserManager<ApplicationUser> usermanager;
        private readonly IprofileService profileService;
        private readonly IPostService postService;

        public ProfileController(UserManager<ApplicationUser> usermanager, IprofileService profileService, IPostService postService)
        {
            this.usermanager = usermanager;
            this.profileService = profileService;
            this.postService = postService;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await usermanager.GetUserAsync(User);
            var model = new UserViewModel
            {
                Address = currentUser.Address,
                FirstName = currentUser.FirstName,
                LastName = currentUser.LastName,
                AvatarUrl = currentUser.AvatarUrl,
                CreatedOn = currentUser.CreatedOn,
                Username = currentUser.UserName,
                Email = currentUser.Email,
                Phone = currentUser.PhoneNumber,

            };
            return View(model);
        }

        public async Task<IActionResult> ShowProfile(string username)
        {
            var currentUser = await usermanager.GetUserAsync(User);
            if (username == currentUser.UserName)
            {
                return RedirectToAction("Index");
            }
            var model = this.profileService.GetByUsername(username);
            return View(model);
        }


    }
}

WodApp/WodApp/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WodApp.Controllers
{
    public class SettingsController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Test"] = "http://res.cloudinary.com/radotooo/image/upload/v1587114349/Test.png";
            return View();
        }
    }
}

WodApp/WodApp/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<Wod.Data.ApplicationUser> UserManager

<!doctype html>

<html lang="en">
<head>

    <title>@ViewData["Title"] - WodApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>

    <div class="wrapper d-flex align-items-stretch">

        <nav id="sidebar" style="background-color:darkred">
            <div class="custom-menu">
                <button type="button" id="sidebarCollapse" class="btn btn-primary">
                </button>
            </div>
            <div class="img bg-wrap text-center py-4" style="background-image: url(/images/bg_1.jpg);">
                <div class="user-logo">
                    <div class="img" style="background-image: url('@UserManager.GetUserAsync(User).Result.AvatarUrl');"></div>
                    <h3>@UserManager.GetUserAsync(User).Result.UserName</h3>
                </div>
            </div>
            <ul class="list-unstyled components mb-5">
                <li class="active">
                    <a asp-area="" asp-controller="Home" asp-action="Index"><span class="fa fa-home mr-3"></span> Home</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Post" asp-action="Create"><span class="fa fa-plus mr-3"><small class="d-flex align-items-center justify-content-center"></small></span> Create Post</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Favorite"><span class="fa fa-gift mr-3"></span> Favorite</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-trophy mr-3"></span> Top Review</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Profile" asp-action="Index"><span class="fa fa-user mr-3"></span> Profile</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-support mr-3"></span> Support</a>

                </li>
                <li>
                    <a asp-controller="Home" asp-action="SingOut" asp-route-returnUrl="@Url.Action("Index","Home")"><span class="fa fa-sign-out mr-3"></span> Sign Out</a>
                </li>
            </ul>

        </nav>

        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5 pt-5">

            @RenderBody()

        </div>
    </div>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/js/popper.js"></script>
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

WodApp/WodApp/Views/Shared/_CookieConsentPartialView.cshtml
@using Microsoft.AspNetCore.Http.Features

@{
    var consentFeature = Context.Features.Get<ITrackingConsentFeature>();
    var showBanner = !consentFeature?.CanTrack ?? false;
    var cookieString = consentFeature?.CreateConsentCookie();
}

@if (showBanner)
{
    <div id="cookieConsent" class="alert alert-info alert-dismissible fade show" role="alert">
        Use this space to summarize your privacy and cookie use policy. <a asp-controller="Home" asp-action="Privacy">Learn More</a>.
        <button type="button" class="accept-policy close" data-dismiss="alert" aria-label="Close" data-cookie-string="@cookieString">
            <span aria-hidden="true">Accept</span>
        </button>
    </div>
    <script>
        (function () {
            var button = document.querySelector("#cookieConsent button[data-cookie-string]");
            button.addEventListener("click", function (event) {
                document.cookie = button.dataset.cookieString;
            }, false);
        })();
    </script>
}

WodApp/WodApp/Views/Shared/_IndexPartial.cshtml
@model Wod.Models.WodApp.VIewModels.Post.IndexPostViewModel

@{
    ViewData["Title"] = "Home Page";


}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/v4-shims.css">



@User.Identity.IsAuthenticated;
----
@User.IsInRole("Admin");
<h4>OrderBy:</h4>

<button id="sortCreate" class="btn btn-secondary active">Fresh</button>
<button id="sortLike" class="btn btn-secondary disabled">Hot</button>

<div id="CreatedOn">
    @{
        foreach (var post in Model.Posts.OrderByDescending(x => x.CreatedOn))
        {

            <div class="container" id"normal">
                <div class="row d-flex justify-content-center">
                    <div class="span8 ">
                        <div class="row d-flex justify-content-center">
                            <div class="span8">
                                <h4><strong><a asp-controller="Post" asp-action="ShowPost" asp-route-id="@post.Id">@post.Tittle</a></strong></h4>
                            </div>
                        </div>
                        <div class="row">

                            <div style="text-align: center;">
                                <img src="@post.PictureUrl" style="max-width: 50%; height: auto;" alt="FYI, image alt text is required" />
                            </div>

                            <form id="votesForm" method="post"></form>

                        </div>
                        <div class="row d-flex justify-content-center">
                            <div class="span8">
                                <p></p>
                                <p>
                                    <i class="fa fa-user"></i> by <a asp-controller="Profile" asp-action="ShowProfile" asp-route-username="@post.UserUsernameName">@post.UserUsernameName</a>
                                    | <i class="fa fa-calendar" style="color:Highlight"></i> @post.CreatedOn.ToString("MM/dd/yyyy hh:mm tt")
                                    | <i class="fa fa-comment"></i> <a asp-controller="Post" asp-action="ShowPost" asp-route-id="@post.Id">Comments @post.Comments.Count()</a>
                                    | <i class="fas fa-plus"></i> <a href="javascript:void(0);" onclick="vote(@post.Id,'@ViewData["userId"]','@post.Tittle')">Add to Favorites </a>
                                    | <i class="fas fa-tags"></i> Tags : <a asp-controller="Category" asp-route-category="@post.CategoryName"><span class="label label-info">@post.CategoryName</span></a>
                                    @*<a href="javascript:void(0);" id="@voteId" onclick="vote(@post.Id, true)"> <button id=" class="fas fa-arrow-up" style="color:darkgrey"></button>  </a>*@
                                    @*<a href="javascript:void(0);" id="@voteId" onclick="vote(@post.Id,false)">  <i class="fas fa-thumbs-down active" style="color:darkgrey"></i></a>*@ <span>@post.VoteCount</span> points

                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
        }
    }
</div>
<div id="Likes" style="display: none">
    @{
        foreach (var post in Model.Posts.OrderByDescending(x => x.VoteCount))
        {

            <div class="container" id"normal">
                <div class="row d-flex justify-content-center">
                    <div class="span8 ">
                        <div class="row d-flex justify-content-center">
                            <div class="span8">
                                <h4><strong><a asp-controller="Post" asp-action="ShowPost" asp-route-id="@post.Id">@post.Tittle</a></strong></h4>
                            </div>
                        </div>
                        <div class="row">

                            <div style="text-align: center;">
                                <img src="@post.PictureUrl" style="max-width: 50%; height: auto;" alt="FYI, image alt text is required" />
                            </div>


                        </div>
                        <div class="row d-flex justify-content-center">
                            <div class="span8">
                                <p></p>
                                <p>
                                    <i class="fa fa-user"></i> by <a asp-controller="Profile" asp-action="ShowProfile" asp-route-username="@post.UserUsernameName">@post.UserUsernameName</a>
                                    | <i class="fa fa-calendar" style="color:Highlight"></i> @post.CreatedOn.ToString("MM/dd/yyyy hh:mm tt")
                                    | <i class="fa fa-comment"></i> <a asp-controller="Post" asp-action="ShowPost" asp-route-id="@post.Id">Comments @post.Comments.Count()</a>
                                    | <i class="fas fa-share"></i> <a href="javascript:void(0);" onclick="vote(@post.Id,'@ViewData["userId"]','@post.Tittle')">Add to Favorites</a>
                                    | <i class="fas fa-tags"></i> Tags : <a asp-controller="Category" asp-route-category="@post.CategoryName"><span class="label label-info">@post.CategoryName</span></a>
                                    @*<a href="javascript:void(0);" id="@voteId" onclick="vote(@post.Id, true)"> <button id=" class="fas fa-arrow-up" style="color:darkgrey"></button>  </a>*@
                                    @*<a href="javascript:void(0);" id="@voteId" onclick="vote(@post.Id,false)">  <i class="fas fa-thumbs-down active" style="color:darkgrey"></i></a>*@ <span>@post.VoteCount</span> points

                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
        }
    }
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active">
                <span class="page-link">
                    2
                    <span class="sr-only">(current)</span>
                </span>
            </li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </nav>
</div>
<script>

    $("#sortLike").click(function () {

        $("#Likes").show();
        $("#sortLike").removeClass('disabled').addClass('active');
        $("#CreatedOn").hide();
        $("#sortCreate").removeClass('active').addClass('disabled');
    });
    $("#sortCreate").click(function () {

        $("#CreatedOn").show();
        $("#sortCreate").removeClass('disabled').addClass('active');
        $("#Likes").hide();
        $("#sortLike").removeClass('active').addClass('disabled');
    });

</script>
<script>
    function vote(postId, userId, name) {

        var token = $("#votesForm input[name=__RequestVerificationToken]").val();

        var json = { postId: postId, userId: userId, tittle: name };

        $.ajax({
            url: "/api/Favorite",
            type: "POST",
            data: JSON.stringify(json),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            headers: { 'X-CSRF-TOKEN': token },
            success: function (data) {
                //$("#votesCount").html(data.count);
                alert(data.message);
            }
        });

    };
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

WodApp/WodApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - WodApp</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-primary bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyApp</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    @*<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Test">Test</a>
                            </li>
                        </ul>
                    </div>*@
                </div>
            </nav>
        </header>
        <div class="container">
            <partial name="_CookieConsentPartialView" />
            <main role="main" class="pb-3">

                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - WodApp - <a asp-area="Identity" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
       
    </body>

    </html>


  

WodApp/WodApp/Views/Shared/_Layout2.cshtml
<!doctype html>

<html lang="en">
<head>
    
    <title>@ViewData["Title"] - WodApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>

    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
            <div class="custom-menu">
                <button type="button" id="sidebarCollapse" class="btn btn-primary">
                </button>
            </div>
            <div class="img bg-wrap text-center py-4" style="background-image: url(/images/bg_1.jpg);">
                <div class="user-logo">
                    <div class="img" style="background-image: url('https://i.pinimg.com/564x/3f/06/e6/3f06e6d1bfc6f9210d8b28979fb534de.jpg');"></div>
                    <h3>@User.Identity.Name</h3>
                </div>
            </div>
            <ul class="list-unstyled components mb-5">
                <li class="active">
                    <a asp-controller="Home" asp-action="Index"><span class="fa fa-home mr-3"></span> Home</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-download mr-3 notif"><small class="d-flex align-items-center justify-content-center">5</small></span> Download</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-gift mr-3"></span> Gift Code</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-trophy mr-3"></span> Top Review</a>
                </li>
                <li>
                    <a asp-controller="Settings" asp-action="Index"><span class="fa fa-cog mr-3"></span> Settings</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-support mr-3"></span> Support</a>

                </li>
                <li>
                    <a asp-controller="Home" asp-action="SingOut" asp-route-returnUrl="@Url.Action("Index","Home")"><span class="fa fa-sign-out mr-3"></span> Sign Out</a>
                </li>
            </ul>

        </nav>

        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5 pt-5">

            @RenderBody()
           
        </div>
    </div>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="~/js/popper.js"></script>
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

WodApp/WodApp/Views/Shared/_LayoutUser.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<Wod.Data.ApplicationUser> UserManager

<!doctype html>

<html lang="en">
<head>

    <title>@ViewData["Title"] - WodApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>

    <div class="wrapper d-flex align-items-stretch">

        <nav id="sidebar" >
            <div class="custom-menu">
                <button type="button" id="sidebarCollapse" class="btn btn-primary">
                </button>
            </div>
            <div class="img bg-wrap text-center py-4" style="background-image: url(/images/bg_1.jpg);">
                <div class="user-logo">
                    <div class="img" style="background-image: url('@UserManager.GetUserAsync(User).Result.AvatarUrl');"></div>
                    <h3>@UserManager.GetUserAsync(User).Result.UserName</h3>
                </div>
            </div>
            <ul class="list-unstyled components mb-5">
                <li class="active">
                    <a asp-area="" asp-controller="Home" asp-action="Index"><span class="fa fa-home mr-3"></span> Home</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Post" asp-action="Create"><span class="fa fa-plus mr-3"><small class="d-flex align-items-center justify-content-center"></small></span> Create Post</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Favorite"><span class="fa fa-gift mr-3"></span> Favorite</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-trophy mr-3"></span> Top Review</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Profile" asp-action="Index"><span class="fa fa-user mr-3"></span> Profile</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-support mr-3"></span> Support</a>

                </li>
                <li>
                    <a asp-controller="Home" asp-action="SingOut" asp-route-returnUrl="@Url.Action("Index","Home")"><span class="fa fa-sign-out mr-3"></span> Sign Out</a>
                </li>
            </ul>

        </nav>

        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5 pt-5">

            @RenderBody()

        </div>
    </div>
    
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/js/popper.js"></script>
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

WodApp/WodApp/Views/Shared/_PostViewPartial.cshtml
@*partial view*@
<div class="container" id"normal">
    <div class="row d-flex justify-content-center">
        <div class="span8 ">
            <div class="row d-flex justify-content-center">
                <div class="span8">
                    <h4><strong><a asp-controller="Post" asp-action="ShowPost" asp-route-id="@Model.Id">@Model.Tittle</a></strong></h4>
                </div>
            </div>
            <div class="row">

                <div style="text-align: center;">
                    <img src="@Model.PictureUrl" style="max-width: 50%; height: auto;" alt="FYI, image alt text is required" />
                </div>

                <form id="votesForm" method="post"></form>

            </div>
            <div class="row d-flex justify-content-center">
                <div class="span8">
                    <p></p>
                    <p>
                        <i class="fa fa-user"></i> by <a href="#">@Model.UserUsernameName</a>
                        | <i class="fa fa-calendar" style="color:Highlight"></i> @Model.CreatedOn.ToString("MM/dd/yyyy hh:mm tt")
                        | <i class="fa fa-comment"></i> <a asp-controller="Post" asp-action="ShowPost" asp-route-id="@Model.Id">Comments @Model.Comments.Count()</a>
                        | <i class="fas fa-plus"></i> <a href="javascript:void(0);" onclick="vote(@Model.Id,'@ViewData["userId"]','@Model.Tittle')">Add to Favorites </a>
                        | <i class="fas fa-tags"></i> Tags : <a asp-controller="Category" asp-route-category="@Model.CategoryName"><span class="label label-info">@Model.CategoryName</span></a>
                        @*<a href="javascript:void(0);" id="@voteId" onclick="vote(@post.Id, true)"> <button id=" class="fas fa-arrow-up" style="color:darkgrey"></button>  </a>*@
                        @*<a href="javascript:void(0);" id="@voteId" onclick="vote(@post.Id,false)">  <i class="fas fa-thumbs-down active" style="color:darkgrey"></i></a>*@ <span>@Model.VoteCount</span> points

                    </p>
                </div>
            </div>
        </div>
    </div>
</div>