WodApp/WodApp/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Wod.Models.WodApp.VIewModels.Post;
using Wod.Services.PostService.Contracts;
using Wod.Services.VoteService.Contracts;

namespace WodApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IPostService postService;
        private readonly IVoteSysService voteSysService;

        public CategoryController(IPostService postService,IVoteSysService voteSysService)
        {
            this.postService = postService;
            this.voteSysService = voteSysService;
        }

        
        public IActionResult Index(string category)
        {
            var model = new IndexPostViewModel
            {
                Posts = postService.GetAllPostFromCategory(category)
            };

            foreach (var post in model.Posts)
            {
                post.VoteCount = voteSysService.GetVoteCount(post.Id);
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["userId"] = userId;
            return View(model);
        }
    }
}

WodApp/WodApp/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Wod.Models.WodApp.Inputmodels;
using Wod.Models.WodApp.VIewModels.Post;
using Wod.Services.CommentService.Contracts;

namespace WodApp.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService commentService;

        public CommentController(ICommentService commentService)
        {
            this.commentService = commentService;
        }

        [HttpPost]
        public IActionResult Create(PostVIewModel input)
        {
        
            commentService.Greate(input.CommentModel);
            return this.RedirectToAction("ShowPost", "Post", new { Id = input.CommentModel.PostId });
        }
    }
}

WodApp/WodApp/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Wod.Data;
using Wod.Models.WodApp.Inputmodels;
using Wod.Services.CategoryService.Contracts;
using Wod.Services.Claudinary;
using Wod.Services.Claudinary.Contracts;
using Wod.Services.PostService.Contracts;
using Wod.Services.VoteService.Contracts;

namespace WodApp.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly ICloudinaryService cloudinaryService;
        private readonly ICategoryService categoryService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IVoteSysService voteSysService;

        public PostController(IPostService postService , ICloudinaryService cloudinaryService,
            ICategoryService categoryService, UserManager<ApplicationUser> userManager,IVoteSysService voteSysService)
        {
            this.postService = postService;
            this.cloudinaryService = cloudinaryService;
            this.categoryService = categoryService;
            this.userManager = userManager;
            this.voteSysService = voteSysService;
        }
        public IActionResult Index()
        {

            return View();
        }

        public async Task<IActionResult> ShowPost(int id)
        {
            var model = await postService.GetAsync(id);
            model.VoteCount = voteSysService.GetVoteCount(model.Id);
            return View(model);
        }


        public IActionResult Create()
        {
       
            var categories = this.categoryService.GetAll();
            var model = new CreatePostInputModel
            {
                Categoryes = categories,
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePostInputModel model)
        {
            var categories = this.categoryService.GetAll();
            model.Categoryes = categories;
            


            var user = await this.userManager.GetUserAsync(this.User);
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }
            var coverUrl = await this.cloudinaryService
                .UploadAsync(model.PictureUrl, User.Identity.Name);
            var date = DateTime.UtcNow;
          var postId =  await postService.GreateAsyns(model.Tittle, model.CategoryId, user.Id, date, coverUrl);
            return this.RedirectToAction("ShowPost", new { id= postId});
        }

    }
}

WodApp/WodApp/Views/Post/Create.cshtml
@model Wod.Models.WodApp.Inputmodels.CreatePostInputModel
@{
    var categories = Model.Categoryes.Select(x => new SelectListItem(x.Name, x.Id.ToString()));
}

<div class="container ">
    <div class="row ">
        <form id="form1" method="post" asp-action="Create" enctype="multipart/form-data">
            <div class="form-group col-sm">
                <label>Preview:</label>
                <div><img id="thumbnil" style="width:30%; margin-top:10px;" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" alt="image" /></div>
                <input asp-for="PictureUrl" type="file" accept="image/*" onchange="showMyImage(this)" />
                <span asp-validation-for="PictureUrl" class="text-danger"></span>

                <br />
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Tittle"></label>
                <input asp-for="Tittle" class="form-control" placeholder="Tittle" />
                <span asp-validation-for="Tittle" class="text-danger"></span>
            </div>

            <div class="form-group col-md-6">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" asp-items="categories" class="form-control "><option selected="" disabled="disabled">Choose Category</option>  </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>

            </div>

            <input type="submit" class="btn btn-primary" />
        </form>
    </div>
</div>

<script>
    function showMyImage(fileInput) {
        var files = fileInput.files;
        for (var i = 0; i < files.length; i++) {
            var file = files[i];
            var imageType = /image.*/;
            if (!file.type.match(imageType)) {
                continue;
            }
            var img = document.getElementById("thumbnil");
            img.file = file;
            var reader = new FileReader();
            reader.onload = (function (aImg) {
                return function (e) {
                    aImg.src = e.target.result;
                };
            })(img);
            reader.readAsDataURL(file);
        }
    }
</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

WodApp/WodApp/Views/Post/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/v4-shims.css">
<!------ Include the above in your HEAD tag ---------->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" asp-controller="Post" asp-action="Create">Create</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
<br />
<div class="container">
    <div class="row">
        <div class="span8 ">
            <div class="row ">
                <div class="span8">
                    <h4><strong><a href="#">Title of the post</a></strong></h4>
                </div>
            </div>
            <div class="row">

                <div style="text-align: center;">
                    <img src="https://media.macphun.com/img/uploads/customer/how-to/579/15531840725c93b5489d84e9.43781620.jpg?q=85&w=1340" style="max-width: 50%; height: auto;" alt="FYI, image alt text is required" />
                </div>


            </div>
            <div class="row">
                <div class="span8">
                    <p></p>
                    <p>
                        <i class="fa fa-user"></i> by <a href="#">John</a>
                        | <i class="fa fa-calendar" style="color:Highlight"></i> Sept 16th, 2012
                        | <i class="fa fa-comment"></i> <a href="#">3 Comments</a>
                        | <i class="fas fa-share"></i> <a href="#">39 Shares</a>
                        | <i class="fas fa-tags"></i> Tags : <a href="#"><span class="label label-info">Snipp</span></a>
                        <i class="fas fa-thumbs-up" style="color:Highlight"></i>
                        <i class="fas fa-thumbs-down" style="color:Highlight"></i>
                        <a href="#"><span class="label label-info">Bootstrap</span></a>
                        <a href="#"><span class="label label-info">UI</span></a>
                        <a href="#"><span class="label label-info">growth</span></a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="span8">
            <div class="row">
                <div class="span8">
                    <h4><strong><a href="#">Title of the post</a></strong></h4>
                </div>
            </div>
            <div class="row">
                <div style="text-align: center;">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg" style="max-width: 50%; height: auto;" alt="FYI, image alt text is required" />
                </div>
             
            </div>
            <div class="row">
                <div class="span8">
                    <p></p>
                    <p>
                        <i class="icon-user"></i> by <a href="#">Mark</a>
                        | <i class="icon-calendar"></i> Sept 16th, 2012
                        | <i class="icon-comment"></i> <a href="#">3 Comments</a>
                        | <i class="icon-share"></i> <a href="#">39 Shares</a>
                        | <i class="icon-tags"></i> Tags : <a href="#"><span class="label label-info">Snipp</span></a>
                        <a href="#"><span class="label label-info">Bootstrap</span></a>
                        <a href="#"><span class="label label-info">UI</span></a>
                        <a href="#"><span class="label label-info">growth</span></a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="span8">
            <div class="row">
                <div class="span8">
                    <h4><strong><a href="#">Title of the post</a></strong></h4>
                </div>
            </div>
            <div class="row">
                <div class="span2">
                    <a href="#" class="thumbnail">
                        <img src="http://placehold.it/260x180" alt="">
                    </a>
                </div>
                <div class="span6">
                    <p>
                        Lorem ipsum dolor sit amet, id nec conceptam conclusionemque. Et eam tation option. Utinam salutatus ex eum. Ne mea dicit tibique facilisi, ea mei omittam explicari conclusionemque, ad nobis propriae quaerendum sea.
                    </p>
                    <p><a href="#">Read more</a></p>
                </div>
            </div>
            <div class="row">
                <div class="span8">
                    <p></p>
                    <p>
                        <i class="icon-user"></i> by <a href="#">Mark</a>
                        | <i class="icon-calendar"></i> Sept 16th, 2012
                        | <i class="icon-comment"></i> <a href="#">3 Comments</a>
                        | <i class="icon-share"></i> <a href="#">39 Shares</a>
                        | <i class="icon-tags"></i> Tags : <a href="#"><span class="label label-info">Snipp</span></a>
                        <a href="#"><span class="label label-info">Bootstrap</span></a>
                        <a href="#"><span class="label label-info">UI</span></a>
                        <a href="#"><span class="label label-info">growth</span></a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <hr>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

WodApp/WodApp/Views/Post/ShowPost.cshtml
@using Microsoft.AspNetCore.Identity
@model Wod.Models.WodApp.VIewModels.Post.PostVIewModel
@inject UserManager<Wod.Data.ApplicationUser> userManager

@{
    ViewData["Title"] = "Show Post";
    async Task ShowNestedComments(int? parentId)
    {
        var comments = this.Model.Comments.Where(x => x.ParentId == parentId);

        if (!comments.Any())
        {
            return;
        }
        @foreach (var comment in comments)
        {
            <div class="comment-box">
                <span class="commenter-pic">
                    <img src="@comment.User.AvatarUrl" class="img-fluid">
                </span>
                <span class="commenter-name">
                    <a href="#">@comment.User.UserName</a> <span class="comment-time">@comment.CreatedOn.ToString("MM/dd/yyyy hh:mm tt")</span>
                </span>
                <p class="comment-txt more">@comment.Content</p>
                <div class="comment-meta">

                    <button class="comment-reply reply-popup" onclick="test('@comment.Id')"><i class="fa fa-reply-all" aria-hidden="true"></i> Reply</button>
                </div>
                <div class="comment-box add-comment reply-box" id="content+@comment.Id">
                    <span class="commenter-pic">
                        <img src="@userManager.GetUserAsync(User).Result.AvatarUrl" class="img-fluid">
                    </span>
                    <form id="form1" method="post" asp-controller="Comment" asp-action="Create" enctype="multipart/form-data">
                        <input type="hidden" await asp-for="@Model.CommentModel.ParentId" value="@comment.Id" />
                        <input type="hidden" asp-for="@Model.CommentModel.PostId" value="@Model.Id" />
                        <input type="hidden" asp-for="@Model.CommentModel.UserId" value="@userManager.GetUserId(User)" />
                        <span class="commenter-name">

                            <input placeholder="Add a public reply" asp-for="@Model.CommentModel.Content" />
                            <span asp-validation-for="@Model.CommentModel.Content" class="text-danger"></span>
                            <button type="submit" class="btn btn-default">Reply</button>
                            <button type="reset" class="btn btn-default reply-popup">Cancel</button>
                        </span>
                    </form>
                </div>
                @{ await ShowNestedComments(comment.Id); }

            </div>
        }
    }
}



<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/v4-shims.css">

<!------ Include the above in your HEAD tag ---------->
<style>
    .comments-details button.btn.dropdown-toggle,
    .comments-details .total-comments {
        font-size: 18px;
        font-weight: 500;
        color: #5e5e5e;
    }

    .comments-details {
        padding: 15px 15px;
    }

    .comments .comments .dropdown,
    .comments .dropup {
        position: relative;
    }

    .comments button {
        background-color: transparent;
        border: none;
    }

    .comments .comment-box {
        width: 100%;
        float: left;
        height: 100%;
        background-color: #FAFAFA;
        padding: 10px 10px 10px;
        margin-bottom: 15px;
        border-radius: 5px;
        border: 1px solid #ddd;
    }

    .comments .add-comment {
        background-color: transparent;
        border: none;
        position: relative;
        margin-bottom: 50px;
    }

    .comments .commenter-pic {
        width: 50px;
        height: 50px;
        display: inline-block;
        border-radius: 100%;
        border: 2px solid #fff;
        overflow: hidden;
        background-color: #fff;
    }

    .comments .add-comment .commenter-name {
        width: 100%;
        padding-left: 75px;
        position: absolute;
        top: 20px;
        left: 0px;
    }

    .comments .add-comment input {
        border-top: 0px;
        border-bottom: 1px solid #ccc;
        border-left: 0px;
        border-right: 0px;
        outline: 0px;
        box-shadow: none;
        border-radius: 0;
        width: 100%;
        padding: 0;
        font-weight: normal;
    }

        .comments .add-comment input:focus {
            border-color: #03a9f4;
            border-width: 2px;
        }

    .comments .add-comment button[type=submit] {
        background-color: #03a9f4;
        color: #fff;
        margin-right: 0px;
    }

    .comments .add-comment button {
        background-color: #f5f5f5;
        margin: 10px 5px;
        font-size: 14px;
        text-transform: uppercase;
        float: right;
    }

    .comments .commenter-name .comment-time {
        font-weight: normal;
        margin-left: 8px;
        font-size: 15px;
    }

    .comments p.comment-txt {
        font-size: 15px;
        border-bottom: 1px solid #ddd;
        padding: 0px 0px 15px;
    }

    .comments .commenter-name {
        display: inline-block;
        position: relative;
        top: -20px;
        left: 10px;
        font-size: 16px;
        font-weight: bold;
    }

    .comments .comment-meta {
        font-size: 14px;
        color: #333;
        padding: 2px 5px 0px;
        line-height: 20px;
        float: right;
    }

    .comments .reply-box {
        display: none;
    }

    .comments .replied {
        background-color: #fff;
        width: 95%;
        float: right;
        margin-top: 15px;
    }

    /*======Responsive CSS=======*/
    @@media (max-width: 767px) {
        .comments .commenter-name {
            font-size: 13px;
            top: -5px;
        }

        .comments .commenter-pic {
            width: 40px;
            height: 40px;
        }

        .comments .commenter-name a {
            display: block;
        }

        .comments .commenter-name .comment-time {
            display: block;
            margin-left: 0px;
        }
    }
</style>



<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="span8 ">
            <div class="row d-flex justify-content-center">
                <div class="span8">
                    <h4><strong><a href="#">@Model.Tittle</a></strong></h4>
                </div>
            </div>
            <div class="row ">

                <div style="text-align: center;">
                    <img src="@Model.PictureUrl" style="max-width: 70%; height: auto;" alt="FYI, image alt text is required" />
                </div>

            </div>
            <form id="votesForm" method="post"></form>
            <div class="row row d-flex justify-content-center">
                <div class="span8 ">
                    <p></p>
                    <p>
                        <i class="fa fa-user"></i> by <a href="#">@Model.UserUsernameName</a>
                        | <i class="fa fa-calendar" style="color:Highlight"></i> @Model.CreatedOn.ToString("MMMM dd yyyy")
                        | <i class="fa fa-comment"></i> <a href="#">@Model.Comments.Count()</a>
                        | <i class="fas fa-tags"></i> Tags : <a asp-controller="Category" asp-action="Index" asp-route-category="@Model.CategoryName"><span class="label label-info">@Model.CategoryName</span></a>
                        <a href="javascript:void(0);" onclick="vote(@Model.Id, true)">  <i class="fas fa-thumbs-up active" id="thumbsUp" style="color:darkgrey"></i></a>
                        <a href="javascript:void(0);" onclick="vote(@Model.Id,false)">  <i class="fas fa-thumbs-down active" id="thumbsDown" style="color:darkgrey"></i></a> <span id="votesCount">@Model.VoteCount</span> points

                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="comments">

                    <div class="comment-box add-comment" >
                        <form id="form1" method="post" asp-controller="Comment" asp-action="Create" enctype="multipart/form-data">
                            <span class="commenter-pic">
                                <img src="@userManager.GetUserAsync(User).Result.AvatarUrl" class="img img-fluid">
                            </span>
                            <input type="hidden" asp-for="@Model.CommentModel.ParentId" value="@null" />
                            <input type="hidden" asp-for="@Model.CommentModel.PostId" value="@Model.Id" />
                            <input type="hidden" asp-for="@Model.CommentModel.UserId" value="@userManager.GetUserId(User)" />
                            <span class="commenter-name">
                                <input placeholder="Add a public comment" asp-for="@Model.CommentModel.Content" />
                                <span asp-validation-for="@Model.CommentModel.Content" class="text-danger"></span>
                                <button type="submit" class="btn btn-default">Comment</button>
                                <button type="reset" class="btn btn-default">Cancel</button>
                            </span>
                        </form>
                    </div>

                    @{await ShowNestedComments(null); }


                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}



<script>
    function vote(postId, VoteType) {
        var token = $("#votesForm input[name=__RequestVerificationToken]").val();
        var json = { postId: postId, VoteType: VoteType };
        $.ajax({
            url: "/api/Vote",
            type: "POST",
            data: JSON.stringify(json),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            headers: { 'X-CSRF-TOKEN': token },
            success: function (data) {
                $("#votesCount").html(data.count);
            }
        });
    };
</script>


<script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

<script>
    $("#thumbsUp").click(function () {
        $("#thumbsUp").css("color", "blue");
        $("#thumbsDown").css("color", "darkgrey");
    });
    $("#thumbsDown").click(function () {
        $("#thumbsDown").css("color", "red");
        $("#thumbsUp").css("color", "darkgrey");
    });

</script>

<script>
    // Reply box popup JS
    $(document).ready(function () {
        $(".reply-popup").click(function () {
            
            $(".reply-box").toggle();
        });
    });
</script>